### ISSUE TITLE
Option to choose buttons in status bar

### ISSUE THREAD

**Issue by it-sha** [prodypanda/copytabs#1]
Thanks for a great extension.

Could you add an option to choose the showed button in the status bar?
For example, I no need CopyCustom and I would like to use the status bar space for other things

**Comment by prodypanda** [comment]
Hi @it-sha,

Thank you for your feedback and kind words about the extension! We're always looking for ways to improve and make the extension more flexible for our users.

I'm happy to inform you that we've implemented your suggestion in the latest version (0.1.2) of the extension. You can now choose which buttons to show in the status bar.

Here's how you can customize the status bar buttons:

1. Open your VS Code settings (File > Preferences > Settings)
2. Search for "copytabs" in the settings search bar
3. You'll find three new options:
   - `copytabs.showCopyAllButton`
   - `copytabs.showCopySelectedButton`
   - `copytabs.showCopyCustomButton`
4. Set these to `true` or `false` based on which buttons you want to see.

Or for example, to hide the "Copy Custom" button, you can add this to your `settings.json`:

```json
"copytabs.showCopyCustomButton": false
```
We hope this update meets your needs and helps you optimize your workspace. If you have any questions about using these new settings or any other feedback, please don't hesitate to let us know.
Thanks again for your valuable input!
