### ISSUE TITLE
Option to copy content directly to clipboard

### ISSUE THREAD

**Issue by it-sha** [prodypanda/copytabs#2]
Hi :) Thanks for the great app!

Do we have the option to copy tabs cotnent directly to the clipboard? Without new tab

This would streamline and speed up workflow

**Comment by prodypanda** [comment]
Thank you for the great suggestion! I'm happy to announce that this feature has been implemented in version **0.2.0** of the extension.

You can now toggle between copying to clipboard or opening in a new tab using:
- A new status bar item: Click "$(clippy) Clipboard Mode" or "$(window) Tab Mode" to toggle
- Command Palette: Use "Toggle Clipboard Mode"
- Keyboard shortcut: `Ctrl+Shift+T` (Windows/Linux) or `Cmd+Shift+T` (macOS)

You can also set the default behavior in your VS Code settings:
```json
{
    "copytabs.copyToClipboard": true
}
```

The mode you choose will apply to all copy operations (Copy All, Copy Selected, and Copy Custom Format).

Please update to the latest version to access this feature. Let me know if you have any questions or if there's anything else you'd like to see added to the extension!
